neutral = [
    "Did you know, starting a semester 2 weeks late will cause mayhem and carnege as the semester draws to a close",
    "Nobody knows who named the earth",
    "Zero does not exist in nature",
    "Without zero, modern electronics wouldn't exist",
    "'Loganamnosis' is an obsessive searching for a forgotten word",
    "Candyfloss was invented by a dentist",
    "In the 10 seasons of 'Friends', the 6 main characters drink 1154 cups of coffee",
    "In 2017, Glasgow was voted the most dangerous and also the friendliest city in Scotland",
    "The Hitler Youth only drank decaf coffee",
    "More than half of all meetings start late",
    "France has short-story vending machines",
    "80 percent of the 'Close Door' buttons in lifts are just for show: the doors are on a timer",
    "Pogonotrophy is the cultivation of a beard",
    "A 'Petarade' is a series of farts",
    "A quarter of british nurses are obese",
    "No-one knows why shower curtains cling to you",
    "A fatal dose of water is 6 litres",
    "'Mano a Mano' means 'hand to hand' not 'man to man'",
    "As longs as you use soap, washing your hands works just as well if the water is cold",
    "(6x9) + (6+9) = 69",
    "Deaf people don't say 'achoo!' when they sneeze",
    "No-one knows how aspirin works",
    "Postgraduate students are 6 time as depressed as the rest of us",
    "The oceans are getting louder",
    "Darkness moves faster then light",
    "Beyoncé has released more perfumes than albums",
    "The first director of 'Jaws' was fired because he kept calling the shark a whale",
    "Angela Merkel has an ambition to host her own TV talk show",
    "The president of Rwanda is an Arsenal fan",
    "Everyone has a unquie tongue print",
    "Colgate has trademarked the Tooth Fairy",
    "69 ant's nests in the UK have listed building status",
    "iTunes customers have to agree not to use Apple products to create nuclear weapons",
    "The Romans drank turpentine to treat depression",
    "A group of pandas is called an 'embarrassment",
    "Not all humans have methaine in their farts",
    "Glaciers can move faster than a speeding train",
    "Horror Films are the only movie genre in which more women appear than men",
    "At 3pm on Christmas Eve, 40 percent of Swedes watch Donald Duck",
    "Queen Victoria owned a bulletproof umbrella",
    "Bats have regional accents",
    "Experts has warned people not to boil their underwear in hot kettles",
    "Looking at photos of puppies and kittens helps you concentrate",
    "The record distance for throwing a paper plane is 69.14 metres",
    "Dogs see in blue and yellow",
    "Lizards in New Guinea have lime-green blood"
    
]